name: pymusas
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - nbgitpuller # This is a special Binder requirement
    - "requests>=2.13.0,<3.0"
    - "spacy>=3.1.4"
    - "srsly>=2.4.1,<3.0"
    - "tqdm>=4.50.0,<5.0"
    - "typer>=0.3.0,<1.0.0"
    - "torch>=2.2,<3.0"
    - "transformers>=4.0,<5.0"
    - "wsd-torch-models>0.1.1,<1.0"
    - "coverage[toml]>=6.0.0"
    - "flake8>=3.8"
    - "isort>=6.0"
    - "mypy>=1.12"
    - "pytest>=6.0,!=7.1.0,!=8.1.0,<9.0.2"
    - "responses>=0.25.7"
    - "tomli-w>=1.2.0"
    - "types-requests>=2.32.4.20250913"
